on: [push]

jobs:
  instant-access:
    runs-on: ubuntu-latest
    name: A job for testing
    steps:
      - name: Test instant access action
        id: test
        uses: erguotou520/instant-access-action@v1
        with:
          channel: "d255d62caef24a3bb66c3465dad70407"
          head: "Instant access action build result"
          body: '{{author}} commit "{{commitMessage}}" at {{commitTime}} with hash {{commitHash}}'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.test.outputs.time }}"
